package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/vanducng/vd-cli/internal/config"
)

func newInitCmd() *cobra.Command {
	var forceFlag bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Create skills.toml at the repo root",
		Long: `Walk up from the current directory to find .git/, then write a starter
skills.toml there. Pass --root <path> to override the walk, or set the
VD_ROOT env var to point at a fixed repo root (--root takes precedence).`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			root, err := resolveRepoRoot(flagRoot)
			if err != nil {
				return err
			}

			dest := filepath.Join(root, "skills.toml")

			if _, statErr := os.Stat(dest); statErr == nil && !forceFlag {
				return fmt.Errorf("skills.toml already exists at %s; use --force to overwrite", dest)
			}

			// Seed bundle defaults from the live marketplace.json if present.
			marketplacePath := filepath.Join(root, ".claude-plugin", "marketplace.json")
			m := &config.Manifest{}
			config.ApplyDefaults(m, marketplacePath)

			template := buildInitTemplate(m)
			if err := os.WriteFile(dest, []byte(template), 0o644); err != nil {
				return fmt.Errorf("write skills.toml: %w", err)
			}

			if !flagQuiet {
				_, _ = fmt.Fprintf(cmd.OutOrStdout(), "created %s\n", dest)
			}
			return nil
		},
	}

	cmd.Flags().BoolVar(&forceFlag, "force", false, "Overwrite existing skills.toml")
	return cmd
}

// buildInitTemplate renders a commented starter skills.toml from seeded defaults.
func buildInitTemplate(m *config.Manifest) string {
	b := m.Targets.Claude.Bundle
	var sb strings.Builder

	sb.WriteString("# skills.toml — vd manifest\n")
	sb.WriteString("# Generated by 'vd init'. Edit freely; 'vd init --force' regenerates from defaults.\n")
	sb.WriteString("\n")
	sb.WriteString("[meta]\n")
	sb.WriteString("  version = 1\n")
	sb.WriteString("\n")

	sb.WriteString("# Declare remote skill sources here.\n")
	sb.WriteString("# [sources.example]\n")
	sb.WriteString("#   type = \"git\"\n")
	sb.WriteString("#   url  = \"https://github.com/some-org/skills\"\n")
	sb.WriteString("#   ref  = \"main\"  # branch, tag, or SHA; optional\n")
	sb.WriteString("\n")

	sb.WriteString("# Track a skill from a declared source.\n")
	sb.WriteString("# mode options: tracked (follow HEAD), pinned (locked SHA), detached (local-only)\n")
	sb.WriteString("# [skills.example]\n")
	sb.WriteString("#   source = \"example\"   # must match a [sources.*] key\n")
	sb.WriteString("#   path   = \"skills/example\"\n")
	sb.WriteString("#   mode   = \"tracked\"\n")
	sb.WriteString("\n")
	sb.WriteString("# [skills.pinned-example]\n")
	sb.WriteString("#   source = \"example\"\n")
	sb.WriteString("#   path   = \"skills/example\"\n")
	sb.WriteString("#   mode   = \"pinned\"\n")
	sb.WriteString("#   pin    = \"abc1234\"   # full or short git SHA\n")
	sb.WriteString("\n")
	sb.WriteString("# Existing skills under skills/ with no declared source are treated as\n")
	sb.WriteString("# mode=detached automatically (auto-detection arrives in phase 03/04).\n")
	sb.WriteString("# [skills.local-only]\n")
	sb.WriteString("#   mode = \"detached\"\n")
	sb.WriteString("\n")

	// Emit [targets.claude] with seeded values.
	sb.WriteString("# Claude Code plugin emission settings (used by 'vd build').\n")
	sb.WriteString("[targets.claude]\n")
	fmt.Fprintf(&sb, "  mode = %q\n", m.Targets.Claude.Mode)
	sb.WriteString("\n")
	sb.WriteString("[targets.claude.bundle]\n")
	fmt.Fprintf(&sb, "  name             = %q\n", b.Name)
	fmt.Fprintf(&sb, "  version          = %q\n", b.Version)
	fmt.Fprintf(&sb, "  description      = %q\n", b.Description)
	fmt.Fprintf(&sb, "  source           = %q\n", b.Source)
	fmt.Fprintf(&sb, "  category         = %q\n", b.Category)
	fmt.Fprintf(&sb, "  homepage         = %q\n", b.Homepage)
	fmt.Fprintf(&sb, "  license          = %q\n", b.License)
	fmt.Fprintf(&sb, "  version_strategy = %q\n", b.VersionStrategy)
	sb.WriteString("\n")

	sb.WriteString("# Per-skill marketplace metadata overrides (used by 'vd build' in phase 05).\n")
	sb.WriteString("# [plugin.vd]\n")
	sb.WriteString("#   description = \"Override plugin description\"\n")
	sb.WriteString("#   version     = \"1.2.3\"   # overrides lock SHA short when set\n")
	sb.WriteString("#   category    = \"utilities\"\n")
	sb.WriteString("#   homepage    = \"https://example.com\"\n")

	return sb.String()
}
