package inventory

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	vdsync "github.com/vanducng/vd-cli/v2/internal/sync"
)

// fixtureRepo builds a repo with one tracked skill (alpha) whose lock tree_hash
// matches the FS (clean) and returns the repo root.
func fixtureRepo(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "skills", "alpha", "SKILL.md"),
		"---\nname: alpha\ndescription: alpha skill\n---\nhello\n")

	hash, err := vdsync.TreeHash(filepath.Join(root, "skills", "alpha"))
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(root, "skills.toml"),
		"[meta]\nversion = 1\n\n[sources.up]\ntype = \"git\"\nurl = \"https://example.com/r\"\n\n[skills.alpha]\nsource = \"up\"\npath = \"skills/alpha\"\nmode = \"tracked\"\n")
	writeFile(t, filepath.Join(root, "skills.lock"),
		"# AUTO-GENERATED by vd. Do not edit.\n[skills.alpha]\nsha = \"abc123def4567890\"\ntree_hash = \""+hash+"\"\n")
	return root
}

// newSvc builds a Service with empty Codex/Cursor homes so tests stay hermetic
// (no scanning of the real ~/.agents or ~/.cursor).
func newSvc(t *testing.T, root, claude string) *Service {
	t.Helper()
	s := NewService(root, claude)
	s.CodexHome = t.TempDir()
	s.CursorHome = t.TempDir()
	return s
}

func TestInventory_ManagedCleanAndDiscovered(t *testing.T) {
	root := fixtureRepo(t)
	claude := fixtureClaude(t) // has skills alpha?no -> beta + agents/commands

	inv, err := newSvc(t, root, claude).Inventory()
	if err != nil {
		t.Fatalf("inventory: %v", err)
	}
	if len(inv.Managed) != 1 || inv.Managed[0].Name != "alpha" {
		t.Fatalf("managed = %+v", inv.Managed)
	}
	if inv.Managed[0].Drift != "none" {
		t.Errorf("clean skill drift = %q, want none", inv.Managed[0].Drift)
	}
	if inv.Managed[0].Description != "alpha skill" {
		t.Errorf("managed description = %q", inv.Managed[0].Description)
	}
	if inv.Managed[0].SHA != "abc123de" {
		t.Errorf("short sha = %q", inv.Managed[0].SHA)
	}
	// Discovered should include claude's beta skill + agent + command, none named alpha-managed dupes.
	var sawBeta, sawAgent bool
	for _, d := range inv.Discovered {
		if d.Type == Skill && d.Name == "beta" {
			sawBeta = true
		}
		if d.Type == Agent && d.Name == "rev" {
			sawAgent = true
		}
	}
	if !sawBeta || !sawAgent {
		t.Errorf("discovered missing beta/agent: %+v", inv.Discovered)
	}
}

func TestInventory_LocalDrift(t *testing.T) {
	root := fixtureRepo(t)
	// Mutate the skill so FS hash diverges from the lock tree_hash.
	writeFile(t, filepath.Join(root, "skills", "alpha", "SKILL.md"),
		"---\nname: alpha\ndescription: alpha skill\n---\nEDITED\n")

	inv, err := newSvc(t, root, t.TempDir()).Inventory()
	if err != nil {
		t.Fatalf("inventory: %v", err)
	}
	if inv.Managed[0].Drift != "local" {
		t.Errorf("edited skill drift = %q, want local", inv.Managed[0].Drift)
	}
}

func TestDoctor_ParityWithDrift(t *testing.T) {
	root := fixtureRepo(t)
	rep, err := newSvc(t, root, t.TempDir()).Doctor()
	if err != nil {
		t.Fatalf("doctor: %v", err)
	}
	if len(rep.Entries) != 1 || rep.Entries[0].Skill != "alpha" || rep.Entries[0].Status != "none" {
		t.Fatalf("doctor entries = %+v", rep.Entries)
	}

	// Add an untracked dir → reported as untracked.
	writeFile(t, filepath.Join(root, "skills", "ghost", "SKILL.md"), "x\n")
	rep, _ = newSvc(t, root, t.TempDir()).Doctor()
	var sawGhost bool
	for _, e := range rep.Entries {
		if e.Skill == "ghost" && e.Status == "untracked" {
			sawGhost = true
		}
	}
	if !sawGhost {
		t.Errorf("ghost not reported untracked: %+v", rep.Entries)
	}
}

func TestSkillDetail(t *testing.T) {
	root := fixtureRepo(t)
	svc := newSvc(t, root, t.TempDir())

	d, err := svc.SkillDetail("alpha")
	if err != nil {
		t.Fatalf("detail: %v", err)
	}
	if d.Frontmatter["name"] != "alpha" || !strings.Contains(d.Body, "hello") {
		t.Errorf("detail = %+v", d)
	}
	if d.Drift != "none" || d.Source != "up" {
		t.Errorf("managed summary not populated: %+v", d.AssetSummary)
	}

	if _, err := svc.SkillDetail("nope"); err == nil {
		t.Error("expected ErrNotFound for unknown skill")
	}
}

func TestInventory_MultiPlatform(t *testing.T) {
	root := fixtureRepo(t)
	claude, codex, cursor := t.TempDir(), t.TempDir(), t.TempDir()
	writeFile(t, filepath.Join(codex, "skills", "cdx", "SKILL.md"),
		"---\nname: cdx\ndescription: codex skill\n---\nx\n")
	writeFile(t, filepath.Join(cursor, "rules", "style.mdc"),
		"---\ndescription: cursor rule\n---\nbe nice\n")

	svc := NewService(root, claude)
	svc.CodexHome, svc.CursorHome = codex, cursor
	inv, err := svc.Inventory()
	if err != nil {
		t.Fatal(err)
	}
	plat := map[string]string{}
	for _, d := range inv.Discovered {
		plat[string(d.Type)+"/"+d.Name] = d.Platform
	}
	if plat["skill/cdx"] != PlatformCodex {
		t.Errorf("codex skill platform = %q, want %q", plat["skill/cdx"], PlatformCodex)
	}
	if plat["rule/style"] != PlatformCursor {
		t.Errorf("cursor rule platform = %q, want %q", plat["rule/style"], PlatformCursor)
	}
}

// TestServiceNoNetHTTP guards the Wails-reuse invariant: the inventory package
// must stay transport-agnostic.
func TestServiceNoNetHTTP(t *testing.T) {
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		data, err := os.ReadFile(e.Name())
		if err != nil {
			t.Fatal(err)
		}
		if strings.Contains(string(data), "\"net/http\"") {
			t.Errorf("%s imports net/http — inventory must stay transport-agnostic", e.Name())
		}
	}
}
