package config

import (
	"bytes"
	"errors"
	"fmt"
	"os"

	"github.com/pelletier/go-toml/v2"
)

const lockfileHeader = "# AUTO-GENERATED by vd. Do not edit.\n"

// Lockfile holds the resolved state of every tracked skill.
type Lockfile struct {
	// Generated is an RFC3339 timestamp set when the lock was last written.
	Generated string               `toml:"generated"`
	Skills    map[string]LockEntry `toml:"skills"`
}

// LockEntry captures the resolved coordinates of one skill at lock time.
type LockEntry struct {
	SHA      string `toml:"sha"`       // full upstream commit SHA
	TreeHash string `toml:"tree_hash"` // SHA-256 of the copied skill tree (dirty detection)
	Source   string `toml:"source"`    // resolved URL of the upstream source
	Path     string `toml:"path"`      // sub-path within the source
	Size     int64  `toml:"size"`      // total bytes of vendored files
	Mtime    string `toml:"mtime"`     // RFC3339 mtime of the HEAD file in the skill
}

// LoadLock reads path and returns a Lockfile.
// If the file does not exist, an empty Lockfile is returned (not an error).
func LoadLock(path string) (*Lockfile, error) {
	l := &Lockfile{
		Skills: make(map[string]LockEntry),
	}

	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return l, nil
		}
		return nil, fmt.Errorf("read %s: %w", path, err)
	}

	// Strip the auto-generated header comment before parsing.
	trimmed := bytes.TrimPrefix(data, []byte(lockfileHeader))

	if err := toml.Unmarshal(trimmed, l); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}

	if l.Skills == nil {
		l.Skills = make(map[string]LockEntry)
	}

	return l, nil
}

// SaveLock atomically writes the lockfile to path with the auto-generated header.
// Map keys are serialized in alphabetic order by pelletier/go-toml/v2.
func SaveLock(path string, l *Lockfile) error {
	var buf bytes.Buffer
	buf.WriteString(lockfileHeader)

	enc := toml.NewEncoder(&buf)
	if err := enc.Encode(l); err != nil {
		return fmt.Errorf("encode lockfile: %w", err)
	}

	return atomicWrite(path, buf.Bytes())
}
