package config

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestLockRoundTrip(t *testing.T) {
	original := &Lockfile{
		Generated: "2026-05-05T08:00:00Z",
		Skills: map[string]LockEntry{
			"stagehand": {
				SHA:    "abc1234def5678901234567890abcdef12345678",
				Source: "https://github.com/example/skills",
				Path:   "skills/stagehand",
				Size:   4096,
				Mtime:  "2026-01-01T00:00:00Z",
			},
			"bravo": {
				SHA:    "deadbeef00112233445566778899aabbccddeeff",
				Source: "https://github.com/beta/tools",
				Path:   "skills/bravo",
				Size:   2048,
				Mtime:  "2026-02-01T00:00:00Z",
			},
		},
	}

	dir := t.TempDir()
	lockPath := filepath.Join(dir, "skills.lock")

	if err := SaveLock(lockPath, original); err != nil {
		t.Fatalf("SaveLock: %v", err)
	}

	// Verify the header comment is present.
	data, err := os.ReadFile(lockPath)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !strings.HasPrefix(string(data), "# AUTO-GENERATED by vd. Do not edit.") {
		t.Errorf("lockfile missing auto-generated header; got: %q", string(data[:min(len(data), 60)]))
	}

	loaded, err := LoadLock(lockPath)
	if err != nil {
		t.Fatalf("LoadLock: %v", err)
	}

	if !reflect.DeepEqual(original, loaded) {
		t.Errorf("round-trip mismatch:\n  original: %+v\n  loaded:   %+v", original, loaded)
	}
}

func TestLoadLockMissingFile(t *testing.T) {
	l, err := LoadLock(filepath.Join(t.TempDir(), "no-such.lock"))
	if err != nil {
		t.Fatalf("expected nil error for missing lockfile, got: %v", err)
	}
	if l == nil {
		t.Fatal("expected non-nil Lockfile")
	}
	if len(l.Skills) != 0 {
		t.Errorf("expected empty skills map, got %d entries", len(l.Skills))
	}
}

func TestLoadLockInvalidTOML(t *testing.T) {
	bad := filepath.Join(t.TempDir(), "bad.lock")
	if err := os.WriteFile(bad, []byte("[[[[broken"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := LoadLock(bad)
	if err == nil {
		t.Fatal("expected error for invalid lockfile TOML, got nil")
	}
}

func TestSaveLockEmptySkills(t *testing.T) {
	l := &Lockfile{Generated: "2026-05-05T00:00:00Z", Skills: make(map[string]LockEntry)}
	dir := t.TempDir()
	path := filepath.Join(dir, "empty.lock")
	if err := SaveLock(path, l); err != nil {
		t.Fatalf("SaveLock empty: %v", err)
	}
	loaded, err := LoadLock(path)
	if err != nil {
		t.Fatalf("LoadLock: %v", err)
	}
	if loaded.Generated != l.Generated {
		t.Errorf("Generated mismatch: got %q want %q", loaded.Generated, l.Generated)
	}
}

func TestLoadLockPermissionDenied(t *testing.T) {
	dir := t.TempDir()
	f := filepath.Join(dir, "unreadable.lock")
	if err := os.WriteFile(f, []byte("generated = '2026-01-01T00:00:00Z'\n"), 0o000); err != nil {
		t.Fatal(err)
	}
	if os.Getuid() == 0 {
		t.Skip("root bypasses file permissions")
	}
	_, err := LoadLock(f)
	if err == nil {
		t.Error("expected error for unreadable lockfile, got nil")
	}
}

func TestLoadLockNilSkillsAfterUnmarshal(t *testing.T) {
	// A lockfile with no [skills] section → Skills map should be non-nil.
	dir := t.TempDir()
	f := filepath.Join(dir, "noskills.lock")
	if err := os.WriteFile(f, []byte("generated = '2026-01-01T00:00:00Z'\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	l, err := LoadLock(f)
	if err != nil {
		t.Fatalf("LoadLock: %v", err)
	}
	if l.Skills == nil {
		t.Error("Skills map should not be nil after loading lockfile without [skills]")
	}
}

func TestSaveLockReadOnlyDir(t *testing.T) {
	dir := t.TempDir()
	if err := os.Chmod(dir, 0o555); err != nil {
		t.Skip("cannot chmod temp dir:", err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0o755) })

	l := &Lockfile{Generated: "2026-05-05T00:00:00Z", Skills: make(map[string]LockEntry)}
	err := SaveLock(filepath.Join(dir, "x.lock"), l)
	if err == nil {
		t.Error("expected error saving to read-only dir, got nil")
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
